/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fis.poo.proyectocine;

import javax.swing.JFrame;
import java.awt.*;
import javax.swing.ImageIcon;


/**
 *
 * @author Alex
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximiza la ventana
        setVisible(true);
    }
     
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPeli1 = new javax.swing.JButton();
        btnPeli3 = new javax.swing.JButton();
        btnPeli4 = new javax.swing.JButton();
        btnPeli5 = new javax.swing.JButton();
        btnPeli6 = new javax.swing.JButton();
        btnPeli2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CARTELERA");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del Cine");

        btnPeli1.setBackground(new java.awt.Color(0, 0, 0));
        btnPeli1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPeli1.setForeground(new java.awt.Color(255, 255, 255));
        btnPeli1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\ProyectoCine\\src\\imagenes\\wywh.jpg")); // NOI18N
        btnPeli1.setText("Pelicula 1");
        btnPeli1.setAlignmentY(10.0F);
        btnPeli1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnPeli1.setBorderPainted(false);
        btnPeli1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPeli1.setDefaultCapable(false);
        btnPeli1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeli1.setRequestFocusEnabled(false);
        btnPeli1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeli1ActionPerformed(evt);
            }
        });

        btnPeli3.setBackground(new java.awt.Color(0, 0, 0));
        btnPeli3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPeli3.setForeground(new java.awt.Color(255, 255, 255));
        btnPeli3.setText("Pelicula 3");
        btnPeli3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeli3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeli3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeli3ActionPerformed(evt);
            }
        });

        btnPeli4.setBackground(new java.awt.Color(0, 0, 0));
        btnPeli4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPeli4.setForeground(new java.awt.Color(255, 255, 255));
        btnPeli4.setText("Pelicula 4");
        btnPeli4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeli4ActionPerformed(evt);
            }
        });

        btnPeli5.setBackground(new java.awt.Color(0, 0, 0));
        btnPeli5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPeli5.setForeground(new java.awt.Color(255, 255, 255));
        btnPeli5.setText("Pelicula 5");
        btnPeli5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeli5ActionPerformed(evt);
            }
        });

        btnPeli6.setBackground(new java.awt.Color(0, 0, 0));
        btnPeli6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPeli6.setForeground(new java.awt.Color(255, 255, 255));
        btnPeli6.setText("Pelicula 6");
        btnPeli6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeli6ActionPerformed(evt);
            }
        });

        btnPeli2.setBackground(new java.awt.Color(0, 0, 0));
        btnPeli2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnPeli2.setForeground(new java.awt.Color(255, 255, 255));
        btnPeli2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\ProyectoCine\\src\\imagenes\\virusloc.jpg")); // NOI18N
        btnPeli2.setText("Pelicula 2");
        btnPeli2.setAlignmentY(10.0F);
        btnPeli2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btnPeli2.setBorderPainted(false);
        btnPeli2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPeli2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPeli2.setRequestFocusEnabled(false);
        btnPeli2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPeli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeli2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPeli1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeli2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPeli4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeli3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPeli5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPeli6, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPeli3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPeli5, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPeli1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPeli4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPeli6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPeli2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        btnPeli1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnPeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeli1ActionPerformed
       ImageIcon icon1 = new ImageIcon("src/imagenes/wywh.jpg");
        
    }//GEN-LAST:event_btnPeli1ActionPerformed

    private void btnPeli3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeli3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeli3ActionPerformed

    private void btnPeli4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeli4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeli4ActionPerformed

    private void btnPeli5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeli5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeli5ActionPerformed

    private void btnPeli6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeli6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPeli6ActionPerformed

    private void btnPeli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeli2ActionPerformed
        ImageIcon icon2 = new ImageIcon("src/imagenes/virusloc.jpg");
    }//GEN-LAST:event_btnPeli2ActionPerformed
   
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPeli1;
    private javax.swing.JButton btnPeli2;
    private javax.swing.JButton btnPeli3;
    private javax.swing.JButton btnPeli4;
    private javax.swing.JButton btnPeli5;
    private javax.swing.JButton btnPeli6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
